#!/bin/sh -e
REMOTE_NAME=$1
BRANCH_NAME=${2-master}
 
heroku maintenance:on --remote $REMOTE_NAME
git push $REMOTE_NAME $BRANCH_NAME:master
heroku restart --remote $REMOTE_NAME
heroku run python manage.py deploy --remote $REMOTE_NAME
heroku maintenance:off --remote $REMOTE_NAME