"""changed product id name

Revision ID: 2bf0ed232b95
Revises: 3f2d1eb3d6f3
Create Date: 2013-08-09 19:28:30.139194

"""

# revision identifiers, used by Alembic.
revision = '2bf0ed232b95'
down_revision = '3f2d1eb3d6f3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('product_id', sa.String(length=100), nullable=True))
    op.drop_column('issues', u'productID')
    op.add_column('titles', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('titles', u'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column(u'title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('titles', 'name')
    op.add_column('issues', sa.Column(u'productID', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('issues', 'product_id')
    ### end Alembic commands ###
