"""many to many relationship between users and publishers

Revision ID: 382352e93a37
Revises: 50823d295dcd
Create Date: 2013-08-07 22:15:41.513812

"""

# revision identifiers, used by Alembic.
revision = '382352e93a37'
down_revision = '50823d295dcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishers_users')
    ### end Alembic commands ###
