"""added precision to issues attribute

Revision ID: 39edd70c10ae
Revises: 1da0a7fd0877
Create Date: 2013-09-02 22:36:36.381217

"""

# revision identifiers, used by Alembic.
revision = '39edd70c10ae'
down_revision = '1da0a7fd0877'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
