"""added mail_bundle attribute to user

Revision ID: 3aba5865f2d4
Revises: 9546ca226e4
Create Date: 2013-10-06 16:42:34.493463

"""

# revision identifiers, used by Alembic.
revision = '3aba5865f2d4'
down_revision = '9546ca226e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail_bundles', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mail_bundles')
    ### end Alembic commands ###
