"""added new relationship for pull lists

Revision ID: 41a77603dfe3
Revises: 21c0fa548d82
Create Date: 2013-08-10 17:15:58.637625

"""

# revision identifiers, used by Alembic.
revision = '41a77603dfe3'
down_revision = '21c0fa548d82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles_users')
    ### end Alembic commands ###
