"""added discount_code char attribute to issue

Revision ID: 4fe7a1e6dd8d
Revises: 3aba5865f2d4
Create Date: 2013-10-06 18:53:06.371197

"""

# revision identifiers, used by Alembic.
revision = '4fe7a1e6dd8d'
down_revision = '3aba5865f2d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('discount_code', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'discount_code')
    ### end Alembic commands ###
