"""added people back into comics table

Revision ID: 50823d295dcd
Revises: 5ae574e8bf68
Create Date: 2013-08-07 21:48:53.102747

"""

# revision identifiers, used by Alembic.
revision = '50823d295dcd'
down_revision = '5ae574e8bf68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comics', sa.Column('people', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comics', 'people')
    ### end Alembic commands ###
