"""changed issue attribute to prospective_release_date

Revision ID: 50ddf2a5deee
Revises: 4fe7a1e6dd8d
Create Date: 2013-10-19 18:45:37.307880

"""

# revision identifiers, used by Alembic.
revision = '50ddf2a5deee'
down_revision = '4fe7a1e6dd8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('issues', sa.Column('prospective_release_date', sa.Date(), nullable=True))
    # op.drop_column('issues', u'current_tfaw_release_date')
    op.alter_column('issues', 'current_tfaw_release_date', new_column_name='prospective_release_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('issues', sa.Column(u'current_tfaw_release_date', sa.DATE(), nullable=True))
    # op.drop_column('issues', 'prospective_release_date')
    op.alter_column('issues', 'prospective_release_date', new_column_name='current_tfaw_release_date')
    ### end Alembic commands ###
