"""changed string size in people attribute

Revision ID: 5ae574e8bf68
Revises: be3b9a733b6
Create Date: 2013-08-07 21:47:07.083952

"""

# revision identifiers, used by Alembic.
revision = '5ae574e8bf68'
down_revision = 'be3b9a733b6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comics', u'people')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comics', sa.Column(u'people', mysql.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
