"""last_updated column added to bundle object

Revision ID: 9546ca226e4
Revises: 59187b0de672
Create Date: 2013-10-05 20:38:44.088749

"""

# revision identifiers, used by Alembic.
revision = '9546ca226e4'
down_revision = '59187b0de672'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'last_updated')
    ### end Alembic commands ###
