"""changed string size in people attribute

Revision ID: be3b9a733b6
Revises: 397b62fa5c80
Create Date: 2013-08-07 21:37:41.853424

"""

# revision identifiers, used by Alembic.
revision = 'be3b9a733b6'
down_revision = '397b62fa5c80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
