"""added alternate relationships to issue class

Revision ID: cd38e1164d7
Revises: 35ff9f972d7e
Create Date: 2013-09-01 21:55:56.587114

"""

# revision identifiers, used by Alembic.
revision = 'cd38e1164d7'
down_revision = '35ff9f972d7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('parent_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'parent_id')
    ### end Alembic commands ###
