"""empty message

Revision ID: 289d26dc0608
Revises: 493da0c4802d
Create Date: 2015-03-21 16:13:04.071148

"""

# revision identifiers, used by Alembic.
revision = '289d26dc0608'
down_revision = '493da0c4802d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'connection')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'connection',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('connection_id_seq'::regclass)", nullable=False),
    sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'profile_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column(u'image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column(u'rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'connection_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'connection_pkey')
    )
    ### end Alembic commands ###
