"""empty message

Revision ID: 3b7095f105a6
Revises: 38fdb0088f84
Create Date: 2014-08-27 21:48:34.889189

"""

# revision identifiers, used by Alembic.
revision = '3b7095f105a6'
down_revision = '38fdb0088f84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('publishers', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'secondary_color')
    op.drop_column('publishers', 'primary_color')
    ### end Alembic commands ###
