"""dropped default calendar from user model

Revision ID: 3f5e2cb023a0
Revises: d0b90a116bf
Create Date: 2014-07-28 22:00:22.840682

"""

# revision identifiers, used by Alembic.
revision = '3f5e2cb023a0'
down_revision = 'd0b90a116bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'default_cal')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'default_cal', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###