"""empty message

Revision ID: 493da0c4802d
Revises: 2e4d6fd3a6fa
Create Date: 2015-03-07 22:31:27.141032

"""

# revision identifiers, used by Alembic.
revision = '493da0c4802d'
down_revision = '2e4d6fd3a6fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('old_diamond_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'old_diamond_id')
    ### end Alembic commands ###
