"""Added last_seen attribute to user model

Revision ID: da052429801
Revises: 3f5e2cb023a0
Create Date: 2014-08-01 19:58:51.716771

"""

# revision identifiers, used by Alembic.
revision = 'da052429801'
down_revision = '3f5e2cb023a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
